package com.rudderstack.integration.kotlin.sprig

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import java.io.File

/**
 * Verifies that the POM XML generated by publishing.gradle.kts for the sprig integration module
 * matches the expected content.
 *
 * The test reads the actual POM file produced by the generatePomFileForReleasePublication
 * Gradle task and compares it against a hardcoded expected XML.
 *
 * Version fields are normalised before comparison since they change across releases:
 * - Flat versions (e.g. `1.3.0-SNAPSHOT`) become `x.y.z`
 * - Semver ranges (e.g. `[1.3.0, 2.0.0)`) become `[x.y.z, x.y.z)` to preserve range structure
 */
class SprigPomVerificationTest {

    @Test
    fun `given publishing script generates pom, when pom is read, then it matches expected xml`() {
        val sprigPomFile = File(System.getProperty("sprigPomFile"))

        val generatedPom = sprigPomFile.readText().trimEnd().normalizeVersions()

        assertEquals(expectedSprigPomXml().normalizeVersions(), generatedPom)
    }

    @Test
    fun `given a range and a pinned version, when normalised, then they stay distinguishable`() {
        val range = "<version>[1.7.1, 2.0.0)</version>".normalizeVersions()
        val pinned = "<version>1.9.0</version>".normalizeVersions()

        assertEquals("<version>[x.y.z, x.y.z)</version>", range)
        assertEquals("<version>x.y.z</version>", pinned)
        assertNotEquals(pinned, range)
    }

    /**
     * Normalises the numeric version endpoints inside every `<version>...</version>` element so that
     * version bumps do not break the test, while leaving surrounding syntax intact.
     *
     * Only the `major.minor.patch(-qualifier)?` numbers are replaced with `x.y.z`, so the range
     * delimiters are preserved and a range stays distinguishable from a pinned version:
     *
     * - Semver ranges like `[1.3.0, 2.0.0)` become `[x.y.z, x.y.z)`
     * - Flat versions like `1.3.0-SNAPSHOT` become `x.y.z`
     *
     * This keeps the test able to catch a regression where a range dependency gets pinned to a flat
     * version (or vice versa).
     */
    private fun String.normalizeVersions(): String =
        replace(Regex("""<version>([^<]+)</version>""")) { match ->
            val normalised = match.groupValues[1]
                .replace(Regex("""\d+\.\d+\.\d+(?:-[A-Za-z0-9.]+)?"""), "x.y.z")
            "<version>$normalised</version>"
        }

    /**
     * Expected POM XML for the sprig integration module, generated by publishing.gradle.kts.
     * Version values use placeholders — actual versions are normalised before comparison.
     *
     * - Semver range `[x.y.z, x.y.z)` verifies that the dependency uses a range, not a pinned version
     * - Dependencies come from sprig/build.gradle.kts implementation (runtime) configurations
     *
     * Reference: published POM at
     * https://repo1.maven.org/maven2/com/rudderstack/integration/kotlin/sprig/
     */
    private fun expectedSprigPomXml(): String = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.rudderstack.integration.kotlin</groupId>
          <artifactId>sprig</artifactId>
          <version>x.y.z</version>
          <packaging>aar</packaging>
          <name>Analytics Kotlin SDK</name>
          <description>RudderStack's SDK for android</description>
          <url>https://github.com/rudderlabs/rudder-sdk-kotlin</url>
          <licenses>
            <license>
              <name>MIT License</name>
              <url>https://github.com/rudderlabs/rudder-sdk-kotlin/blob/main/LICENSE.md</url>
              <distribution>repo</distribution>
            </license>
          </licenses>
          <developers>
            <developer>
              <id>Rudderstack</id>
              <name>Rudderstack, Inc.</name>
            </developer>
          </developers>
          <scm>
            <connection>scm:git:git://github.com/rudderlabs/rudder-sdk-kotlin.git</connection>
            <developerConnection>scm:git:git://github.com:rudderlabs/rudder-sdk-kotlin.git</developerConnection>
            <url>https://github.com/rudderlabs/rudder-sdk-kotlin/tree/main</url>
          </scm>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk8</artifactId>
              <version>x.y.z</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>com.rudderstack.sdk.kotlin</groupId>
              <artifactId>android</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>com.userleap</groupId>
              <artifactId>userleap-android-sdk</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>androidx.fragment</groupId>
              <artifactId>fragment-ktx</artifactId>
              <version>x.y.z</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>androidx.core</groupId>
              <artifactId>core-ktx</artifactId>
              <version>x.y.z</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
    """.trimIndent()
}
