package com.rudderstack.integration.kotlin.clevertap

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import java.io.File

/**
 * Verifies that the POM XML generated by publishing.gradle.kts for the clevertap integration module
 * matches the expected content.
 */
class CleverTapPomVerificationTest {

    @Test
    fun `given publishing script generates pom, when pom is read, then it matches expected xml`() {
        val clevertapPomFile = File(System.getProperty("clevertapPomFile"))

        val generatedPom = clevertapPomFile.readText().trimEnd().normalizeVersions()

        assertEquals(expectedCleverTapPomXml().normalizeVersions(), generatedPom)
    }

    /**
     * Replaces all `<version>...</version>` values with placeholders so that
     * version bumps do not break the test.
     */
    private fun String.normalizeVersions(): String =
        replace(Regex("""<version>[^<]+</version>"""), "<version>x.y.z</version>")

    /**
     * Expected POM XML for the clevertap integration module, generated by publishing.gradle.kts.
     * Version values use placeholders — actual versions are normalised before comparison.
     */
    private fun expectedCleverTapPomXml(): String = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.rudderstack.integration.kotlin</groupId>
          <artifactId>clevertap</artifactId>
          <version>x.y.z</version>
          <packaging>aar</packaging>
          <name>Analytics Kotlin SDK</name>
          <description>RudderStack's SDK for android</description>
          <url>https://github.com/rudderlabs/rudder-sdk-kotlin</url>
          <licenses>
            <license>
              <name>MIT License</name>
              <url>https://github.com/rudderlabs/rudder-sdk-kotlin/blob/main/LICENSE.md</url>
              <distribution>repo</distribution>
            </license>
          </licenses>
          <developers>
            <developer>
              <id>Rudderstack</id>
              <name>Rudderstack, Inc.</name>
            </developer>
          </developers>
          <scm>
            <connection>scm:git:git://github.com/rudderlabs/rudder-sdk-kotlin.git</connection>
            <developerConnection>scm:git:git://github.com:rudderlabs/rudder-sdk-kotlin.git</developerConnection>
            <url>https://github.com/rudderlabs/rudder-sdk-kotlin/tree/main</url>
          </scm>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk8</artifactId>
              <version>x.y.z</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>com.rudderstack.sdk.kotlin</groupId>
              <artifactId>android</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>androidx.core</groupId>
              <artifactId>core-ktx</artifactId>
              <version>x.y.z</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>com.clevertap.android</groupId>
              <artifactId>clevertap-android-sdk</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
    """.trimIndent()
}
