package com.rudderstack.sdk.kotlin.core

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals
import java.io.File

/**
 * Verifies that the POM XML generated by publishing.gradle.kts for the core module
 * matches the expected content.
 *
 * The test reads the actual POM file produced by the generatePomFileForReleasePublication
 * Gradle task and compares it against a hardcoded expected XML.
 *
 * Version fields (module version and dependency versions) are normalised to `x.y.z`
 * placeholders before comparison since they change across releases.
 */
class CorePomVerificationTest {

    @Test
    fun `given publishing script generates pom, when pom is read, then it matches expected xml`() {
        val corePomFile = File(System.getProperty("corePomFile"))

        val generatedPom = corePomFile.readText().trimEnd().normalizeVersions()

        assertEquals(expectedCorePomXml(), generatedPom)
    }

    /**
     * Replaces all `<version>...</version>` values with a placeholder so that
     * version bumps do not break the test.
     */
    private fun String.normalizeVersions(): String =
        replace(Regex("""<version>[^<]+</version>"""), "<version>x.y.z</version>")

    /**
     * Expected POM XML for the core module, generated by publishing.gradle.kts.
     * Version values use `x.y.z` placeholders — actual versions are normalised before comparison.
     *
     * - Dependencies come from core/build.gradle.kts api (compile) and implementation (runtime) configurations
     *
     * Reference: published POM at
     * https://repo1.maven.org/maven2/com/rudderstack/sdk/kotlin/core/
     */
    private fun expectedCorePomXml(): String = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.rudderstack.sdk.kotlin</groupId>
          <artifactId>core</artifactId>
          <version>x.y.z</version>
          <name>Analytics Kotlin SDK</name>
          <description>RudderStack's SDK for android</description>
          <url>https://github.com/rudderlabs/rudder-sdk-kotlin</url>
          <licenses>
            <license>
              <name>Elastic License 2.0 (ELv2)</name>
              <url>https://github.com/rudderlabs/rudder-sdk-kotlin/blob/main/LICENSE.md</url>
              <distribution>repo</distribution>
            </license>
          </licenses>
          <developers>
            <developer>
              <id>Rudderstack</id>
              <name>Rudderstack, Inc.</name>
            </developer>
          </developers>
          <scm>
            <connection>scm:git:git://github.com/rudderlabs/rudder-sdk-kotlin.git</connection>
            <developerConnection>scm:git:git://github.com:rudderlabs/rudder-sdk-kotlin.git</developerConnection>
            <url>https://github.com/rudderlabs/rudder-sdk-kotlin/tree/main</url>
          </scm>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlinx</groupId>
              <artifactId>kotlinx-serialization-json</artifactId>
              <version>x.y.z</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk8</artifactId>
              <version>x.y.z</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>org.jetbrains.kotlinx</groupId>
              <artifactId>kotlinx-coroutines-core</artifactId>
              <version>x.y.z</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
    """.trimIndent()
}
