package com.rudderstack.integration.kotlin.firebase

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertEquals
import java.io.File

/**
 * Verifies that the POM XML generated by publishing.gradle.kts for the firebase integration module
 * matches the expected content.
 *
 * The test reads the actual POM file produced by the generatePomFileForReleasePublication
 * Gradle task and compares it against a hardcoded expected XML.
 *
 * Version fields are normalised before comparison since they change across releases:
 * - Flat versions (e.g. `1.3.0-SNAPSHOT`) become `x.y.z`
 * - Semver ranges (e.g. `[1.3.0, 2.0.0)`) become `[x.y.z, x.y.z)` to preserve range structure
 */
class FirebasePomVerificationTest {

    @Test
    fun `given publishing script generates pom, when pom is read, then it matches expected xml`() {
        val firebasePomFile = File(System.getProperty("firebasePomFile"))

        val generatedPom = firebasePomFile.readText().trimEnd().normalizeVersions()

        assertEquals(expectedFirebasePomXml().normalizeVersions(), generatedPom)
    }

    /**
     * Replaces all `<version>...</version>` values with placeholders so that
     * version bumps do not break the test.
     *
     * - Semver ranges like `[1.3.0, 2.0.0)` become `[x.y.z, x.y.z)`
     * - Flat versions like `1.3.0-SNAPSHOT` become `x.y.z`
     */
    private fun String.normalizeVersions(): String =
        replace(Regex("""<version>[^<]+</version>"""), "<version>x.y.z</version>")

    /**
     * Expected POM XML for the firebase integration module, generated by publishing.gradle.kts.
     * Version values use placeholders — actual versions are normalised before comparison.
     *
     * - Semver range `[x.y.z, x.y.z)` verifies that the dependency uses a range, not a pinned version
     * - Dependencies come from firebase/build.gradle.kts implementation (runtime) configurations
     *
     * Reference: published POM at
     * https://repo1.maven.org/maven2/com/rudderstack/integration/kotlin/firebase/
     */
    private fun expectedFirebasePomXml(): String = """
        <?xml version="1.0" encoding="UTF-8"?>
        <project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <modelVersion>4.0.0</modelVersion>
          <groupId>com.rudderstack.integration.kotlin</groupId>
          <artifactId>firebase</artifactId>
          <version>x.y.z</version>
          <packaging>aar</packaging>
          <name>Analytics Kotlin SDK</name>
          <description>RudderStack's SDK for android</description>
          <url>https://github.com/rudderlabs/rudder-sdk-kotlin</url>
          <licenses>
            <license>
              <name>Elastic License 2.0 (ELv2)</name>
              <url>https://github.com/rudderlabs/rudder-sdk-kotlin/blob/main/LICENSE.md</url>
              <distribution>repo</distribution>
            </license>
          </licenses>
          <developers>
            <developer>
              <id>Rudderstack</id>
              <name>Rudderstack, Inc.</name>
            </developer>
          </developers>
          <scm>
            <connection>scm:git:git://github.com/rudderlabs/rudder-sdk-kotlin.git</connection>
            <developerConnection>scm:git:git://github.com:rudderlabs/rudder-sdk-kotlin.git</developerConnection>
            <url>https://github.com/rudderlabs/rudder-sdk-kotlin/tree/main</url>
          </scm>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-stdlib-jdk8</artifactId>
              <version>x.y.z</version>
              <scope>compile</scope>
            </dependency>
            <dependency>
              <groupId>com.rudderstack.sdk.kotlin</groupId>
              <artifactId>android</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>androidx.core</groupId>
              <artifactId>core-ktx</artifactId>
              <version>x.y.z</version>
              <scope>runtime</scope>
            </dependency>
            <dependency>
              <groupId>com.google.firebase</groupId>
              <artifactId>firebase-bom</artifactId>
              <version>[x.y.z, x.y.z)</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </project>
    """.trimIndent()
}
