#!/bin/bash

# Script to create release pull requests
# Usage: ./scripts/create-release-prs.sh "version" "affected_modules" "release_url" [dry_run]
# 
# This script:
# 1. Creates PR from release branch to main
# 2. Creates backmerge PR from release branch to develop
# 3. Only runs for release/hotfix branches

set -e

# Function to create PR to main
create_pr_to_main() {
    local branch_name="$1"
    local version="$2"
    local affected_modules="$3"
    local release_url="$4"
    local dry_run="$5"
    
    if [ "$dry_run" = "true" ]; then
        echo "Dry run mode: skipping PR to main creation"
        return 0
    fi
    
    echo "Creating PR from $branch_name to main..."
    
    local pr_title="Release v$version"
    local pr_body="## Release v$version

This PR merges the release branch \`$branch_name\` into \`main\`.

### Release Details
- **Version**: v$version
- **Release URL**: $release_url
- **Affected Modules**: $affected_modules

### Changes
This release includes all changes from the \`$branch_name\` branch.

**Auto-generated by GitHub Actions**"
    
    # Create PR to main
    gh pr create \
        --title "$pr_title" \
        --body "$pr_body" \
        --base main \
        --head "$branch_name" \
        --label "release" \
        --assignee "$GITHUB_ACTOR" || echo "PR to main may already exist"
    
    echo "✅ PR to main created successfully"
}

# Function to create PR to develop
create_pr_to_develop() {
    local branch_name="$1"
    local version="$2"
    local affected_modules="$3"
    local release_url="$4"
    local dry_run="$5"
    
    if [ "$dry_run" = "true" ]; then
        echo "Dry run mode: skipping PR to develop creation"
        return 0
    fi
    
    echo "Creating backmerge PR from $branch_name to develop..."
    
    local pr_title="Backmerge v$version to develop"
    local pr_body="## Backmerge v$version to develop

This PR backmerges the release branch \`$branch_name\` into \`develop\` to keep both branches in sync.

### Release Details
- **Version**: v$version
- **Release URL**: $release_url
- **Affected Modules**: $affected_modules

### Purpose
This ensures that any release-specific changes (version bumps, etc.) are properly merged back into the develop branch.

**Auto-generated by GitHub Actions**"
    
    # Create PR to develop
    gh pr create \
        --title "$pr_title" \
        --body "$pr_body" \
        --base develop \
        --head "$branch_name" \
        --label "backmerge" \
        --assignee "$GITHUB_ACTOR" || echo "PR to develop may already exist"
    
    echo "✅ PR to develop created successfully"
}

# Function to check if current branch is a release branch
is_release_branch() {
    local branch_name="$1"
    
    if [[ "$branch_name" =~ ^release/.* ]] || [[ "$branch_name" =~ ^hotfix/.* ]]; then
        return 0
    else
        return 1
    fi
}

# Function to validate environment
validate_environment() {
    if [ -z "$GITHUB_TOKEN" ]; then
        echo "❌ GITHUB_TOKEN environment variable is required"
        return 1
    fi
    
    if [ -z "$GITHUB_ACTOR" ]; then
        echo "❌ GITHUB_ACTOR environment variable is required"
        return 1
    fi
    
    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        echo "❌ GitHub CLI (gh) is not installed"
        return 1
    fi
    
    echo "✅ Environment validation passed"
}

# Main function
main() {
    local version="$1"
    local affected_modules="$2"
    local release_url="$3"
    local dry_run="${4:-false}"
    
    if [ -z "$version" ]; then
        echo "❌ Version is required"
        echo "Usage: $0 <version> [affected_modules] [release_url] [dry_run]"
        return 1
    fi
    
    # Get current branch name
    local branch_name
    branch_name="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
    
    echo "🔀 Creating release pull requests"
    echo "Branch: $branch_name"
    echo "Version: $version"
    echo "Affected modules: $affected_modules"
    echo "Release URL: $release_url"
    echo "Dry run: $dry_run"
    echo ""
    
    # Check if this is a release branch
    if ! is_release_branch "$branch_name"; then
        echo "⚠️  Not running on a release/hotfix branch ($branch_name)"
        echo "Skipping PR creation"
        return 0
    fi
    
    echo "✅ Running on release/hotfix branch: $branch_name"
    
    # Validate environment
    validate_environment
    
    # Create PR to main
    create_pr_to_main "$branch_name" "$version" "$affected_modules" "$release_url" "$dry_run"
    
    echo ""
    
    # Create PR to develop
    create_pr_to_develop "$branch_name" "$version" "$affected_modules" "$release_url" "$dry_run"
    
    echo ""
    echo "✅ Release pull requests creation completed successfully"
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
