#!/bin/bash

echo "Running unit tests..."

./gradlew clean # First clean the project
./gradlew test # Run the tests


status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
