name: 'Build Check'
description: 'Build affected modules after quality checks pass'

inputs:
  affected_modules:
    description: 'Comma-separated list of affected modules'
    required: true

outputs:
  affected_modules:
    description: 'Comma-separated list of affected modules (pass-through)'
    value: ${{ inputs.affected_modules }}

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Build affected modules
      shell: bash
      run: |
        chmod +x scripts/run-quality-checks.sh
        ./scripts/run-quality-checks.sh "${{ inputs.affected_modules }}" "build"
