name: 'Detekt Check'
description: 'Run Detekt static analysis on affected modules'

inputs:
  affected_modules:
    description: 'Comma-separated list of affected modules (optional - runs on all modules if not provided)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Run Detekt on affected modules
      shell: bash
      run: |
        chmod +x scripts/run-quality-checks.sh
        if [ -n "${{ inputs.affected_modules }}" ]; then
          ./scripts/run-quality-checks.sh "${{ inputs.affected_modules }}" "detekt"
        else
          # Run on all modules when no affected modules specified
          ./gradlew detekt
        fi

    - name: Upload Detekt reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: detekt-reports-${{ github.run_id }}
        path: |
          **/build/reports/detekt/
