build:
  weights:
    TooGenericExceptionCaught: 0

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'MdOutputReport'
    - 'SarifOutputReport'

comments:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

complexity:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  LongParameterList:
    active: true
    functionThreshold: 12
    constructorThreshold: 12
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []
  NamedArguments:
    active: true
    threshold: 3
    ignoreArgumentsMatchingNames: false
  ReplaceSafeCallChainWithRun:
    active: true
  TooManyFunctions:
    thresholdInFiles: 16
    thresholdInClasses: 16
    thresholdInInterfaces: 16
    thresholdInObjects: 16
    thresholdInEnums: 16

coroutines:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  GlobalCoroutineUsage:
    active: true
  InjectDispatcher:
    active: true
    dispatcherNames:
      - 'IO'
      - 'Default'
      - 'Unconfined'
      - 'Main'
  SuspendFunWithCoroutineScopeReceiver:
    active: true

empty-blocks:
  active: true

exceptions:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - 'Error'
      - 'Exception'
      - 'RuntimeException'
      - 'Throwable'

naming:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  BooleanPropertyNaming:
    active: true
    allowedPattern: '^(is|has|are|should)'
  InvalidPackageDeclaration:
    active: false

performance:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  CouldBeSequence:
    active: true
    threshold: 3
  UnnecessaryPartOfBinaryExpression:
    active: true

potential-bugs:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  CastNullableToNonNullableType:
    active: true
  CastToNullableType:
    active: true
  DontDowncastCollectionTypes:
    active: true
  ElseCaseInsteadOfExhaustiveWhen:
    active: true

style:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  MaxLineLength:
    active: false
  ReturnCount:
    active: true
    max: 4

formatting:
  excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
  active: true
  android: false
  autoCorrect: true
  ArgumentListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    maxLineLength: 125
  ContextReceiverMapping:
    active: false
    autoCorrect: true
    maxLineLength: 125
    indentSize: 4
  EnumWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  FunctionReturnTypeSpacing:
    active: true
    autoCorrect: true
    maxLineLength: 125
  FunctionSignature:
    active: true
    autoCorrect: true
    forceMultilineWhenParameterCountGreaterOrEqualThan: 2147483647
    functionBodyExpressionWrapping: 'default'
    maxLineLength: 125
    indentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 125
    ignoreBackTickedIdentifier: false
  ParameterListWrapping:
    active: true
    autoCorrect: true
    maxLineLength: 125
    indentSize: 4
  ParameterWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    maxLineLength: 125
  PropertyName:
    active: false
  PropertyWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    maxLineLength: 125
  Wrapping:
    active: true
    autoCorrect: true
    indentSize: 4
    maxLineLength: 125
