name: 'Build AARs and JARs'
description: 'Builds AAR/JAR files for library modules and uploads them as artifacts'

inputs:
  affected_modules:
    description: 'Comma-separated list of affected modules'
    required: true

outputs:
  built_modules:
    description: 'Comma-separated list of built modules'
    value: ${{ steps.build-aars.outputs.built_modules }}
  has_artifacts:
    description: 'Whether AAR/JAR artifacts were generated'
    value: ${{ steps.build-aars.outputs.has_artifacts }}

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Build Library Module AARs/JARs
      id: build-aars
      shell: bash
      run: |
        chmod +x scripts/build-aars.sh
        ./scripts/build-aars.sh "${{ inputs.affected_modules }}"

    - name: Upload Library AARs/JARs
      if: steps.build-aars.outputs.has_artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: library-aars-${{ github.run_id }}
        path: |
          core/build/libs/*.jar
          android/build/outputs/aar/*-release.aar
          integrations/*/build/outputs/aar/*-release.aar
        retention-days: 30

    - name: AAR Build Summary
      shell: bash
      run: |
        echo "📦 AAR/JAR Build Summary:"
        echo "Built modules: ${{ steps.build-aars.outputs.built_modules }}"
        echo "Has artifacts: ${{ steps.build-aars.outputs.has_artifacts }}"
