name: Branch Validation

on:
  push:
    branches:
      - 'develop'
      - 'feat/*'
      - 'fix/*'
      - 'refactor/*'
      - 'chore/*'
      - 'release/*'
      - 'hotfix/*'
      - 'ci/*'
    # Removed catch-all pattern to avoid duplicate runs for PR branches

jobs:
  # Check if there's an open PR for this branch
  check-pr-exists:
    name: Check for Open PR
    runs-on: ubuntu-latest
    outputs:
      has-open-pr: ${{ steps.check-pr.outputs.has-open-pr }}
    steps:
      - name: Check for open PR
        id: check-pr
        run: |
          # Get the current branch name
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Checking for open PRs for branch: $BRANCH_NAME"

          # Check if there's an open PR for this branch
          PR_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=${{ github.repository_owner }}:$BRANCH_NAME" \
            | jq length)

          echo "Found $PR_COUNT open PR(s) for this branch"

          if [ "$PR_COUNT" -gt 0 ]; then
            echo "has-open-pr=true" >> $GITHUB_OUTPUT
            echo "✅ Open PR exists - branch validation will be skipped"
          else
            echo "has-open-pr=false" >> $GITHUB_OUTPUT
            echo "❌ No open PR found - branch validation will proceed"
          fi

  # Lightweight code validation without artifacts
  code-validation:
    name: Code Validation
    runs-on: ubuntu-latest
    needs: check-pr-exists
    if: needs.check-pr-exists.outputs.has-open-pr == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for detecting changes

      - name: Setup and Validate
        id: validate
        uses: ./.github/actions/setup-and-validate

      - name: Notify Slack
        if: always()
        run: |
          chmod +x scripts/send-slack-notification.sh
          
          # Determine status
          if [ "${{ job.status }}" = "success" ]; then
            STATUS="passed"
          else
            STATUS="failed"
          fi
          
          # Set environment variables for the script
          export GITHUB_REPOSITORY="${{ github.repository }}"
          export GITHUB_REF_NAME="${{ github.ref_name }}"
          export GITHUB_EVENT_HEAD_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          export GITHUB_ACTOR="${{ github.actor }}"
          export GITHUB_SHA="${{ github.sha }}"
          export SLACK_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          
          ./scripts/send-slack-notification.sh "branch" "$STATUS"

  # SonarCloud analysis for important branches
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: check-pr-exists
    if: needs.check-pr-exists.outputs.has-open-pr == 'false' && contains(fromJson('["develop", "main"]'), github.ref_name)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Run SonarCloud Analysis
        uses: ./.github/actions/sonarcloud-analysis
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
